version: '3.9'
services:
  food-mvc:
    image: yuki10r/food-mvc:0.0.1.RELEASE
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - food-db
    networks:
      - food-network

  # The value of 'DB_HOST' we reference in the MVC Dockerfile
  food-db:
    image: yuki10r/food-db:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - food-network
      
networks:
  food-network: